use serde::{ Deserialize, Serialize };
use chrono::{ DateTime, TimeZone, Utc };
use serde_json::Value;

use crate::{ConceptDeclarationBase, metamodel::{concerto::Concept, utils::*}};
pub use super::concerto_metamodel_1_0_0::*;

impl Clone for Identified {
   fn clone(&self) -> Self {
      Self {
         _class: self._class.clone(),
      }
   }
}

impl Clone for StringLengthValidator {
   fn clone(&self) -> Self {
      Self {
        _class: self._class.clone(),
        min_length: self.min_length.clone(),
        max_length: self.max_length.clone(),
      }
   }
}

impl Clone for MapKeyType{
   fn clone(&self) -> Self{
      Self { _class: self._class.clone(), 
         decorators: self.decorators.clone(), 
         location: self.location.clone() 
      }
   }
}

impl Clone for MapValueType {
   fn clone(&self) -> Self{
      Self { 
         _class: self._class.clone(), 
         decorators: self.decorators.clone(), 
         location: self.location.clone() 
      }
   }
}

impl Clone for MapDeclaration {
   fn clone(&self) -> Self{
      Self{
         _class: self._class.clone(),
         key: self.key.clone(),
         value: self.value.clone(),
         name: self.name.clone(),
         decorators: self.decorators.clone(),
         location: self.location.clone()
      }
   }
}

impl Clone for EnumProperty{
   fn clone(&self) -> Self{
      Self { 
         _class: self._class.clone(), 
         name: self.name.clone(), 
         decorators: self.decorators.clone(), 
         location: self.location.clone() 
      }
   }
}

impl Clone for EnumDeclaration{
   fn clone(&self) -> Self{
      Self { 
         _class: self._class.clone(), 
         properties: self.properties.clone(), 
         name: self.name.clone(), 
         decorators: self.decorators.clone(), 
         location: self.location.clone() 
      }
   }
}

impl Clone for TypeIdentifier{
   fn clone(&self) -> Self{
      Self { 
         _class: self._class.clone(), 
         name: self.name.clone(), 
         namespace: self.namespace.clone() 
      }
   }
}

impl Clone for Property{
   fn clone(&self) -> Self{
      Self { 
         _class: self._class.clone(), 
         name: self.name.clone(), 
         is_array: self.is_array.clone(), 
         is_optional: self.is_optional.clone(), 
         decorators: self.decorators.clone(), 
         location: self.location.clone() 
      }
   }
}

impl Clone for ConceptDeclaration{
   fn clone(&self) -> Self{
      Self { 
         _class: self._class.clone(), 
         is_abstract: self.is_abstract.clone(), 
         identified: self.identified.clone(), 
         super_type: self.super_type.clone(), 
         properties: self.properties.clone(), 
         name: self.name.clone(), 
         decorators: self.decorators.clone(), 
         location: self.location.clone() 
      }
   }
}

// Not present in the concerto-metamodel generated by the codegen
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Type {
   #[serde(
      rename = "$class",
   )]
   pub _class: String,

   #[serde(
      rename = "name",
   )]
   pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Validator {
   #[serde(
      rename = "$class",
   )]
   pub _class: String,

   #[serde(
      rename = "lower",
      skip_serializing_if = "Option::is_none",
   )]
   pub lower: Option<i32>,

   #[serde(
      rename = "upper",
      skip_serializing_if = "Option::is_none",
   )]
   pub upper: Option<i32>,
}

#[derive(Clone, Debug)]
pub enum DeclarationUnion {
   Declaration(super::concerto_metamodel_1_0_0::Declaration),
   MapDeclaration(super::concerto_metamodel_1_0_0::MapDeclaration),
   EnumDeclaration(super::concerto_metamodel_1_0_0::EnumDeclaration),
   ConceptDeclaration(super::concerto_metamodel_1_0_0::ConceptDeclaration),
}

// Not present in the concerto-metamodel generated by the codegen
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Values{
   #[serde(
      rename = "$class",
   )]
   pub _class: String,

   #[serde(
      rename="type",
   )]
   pub r#type: Option<Type>,
}

// Not present in the concerto-metamodel generated by the codegen
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SuperType{
   #[serde(
      rename = "$class",
   )]
   pub _class: String,

   #[serde(
      rename = "name",
   )]
   pub name: String
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Properties {
   #[serde(
      rename = "$class",
   )]
   pub _class: String,

   #[serde(
      rename = "name",
   )]
   pub name: String,

   #[serde(
      rename = "type",
   )]
   pub r#type: Option<Type>,

   #[serde(
      rename = "isOptional",
   )]
   pub is_optional: Option<bool>,

   #[serde(
      rename = "isArray",
   )]
   pub is_array: Option<bool>,

   #[serde(
      rename="decorators",
   )]
   pub decorators: Option<Vec<Decorator>>,

   #[serde(
      rename="validator",
   )]
   pub validator: Option<Validator>,

   #[serde(
      rename="lengthValidator",
   )]
   pub length_validator: Option<StringLengthValidator>
}
