name: Concerto Conformance Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  conformance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Project
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build Target Project
        run: |
          npm install
          npm run build

      - name: Checkout Conformance Suite
        uses: actions/checkout@v3
        with:
          repository: Anshukumar123975/concerto-conformance
          path: concerto-conformance

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Rust-based Conformance Tests
        working-directory: concerto-conformance/semantic/features/support/rust/cucumber_tests
        run: cargo run
